@startuml
usecase przegladanieWydarzen as "Przeglądanie
wydarzeń"
usecase propozycjaWydarzenPublicznych as "Tworzenie propozycji
wydarzeń publicznych"

zalogowany -- przegladanieWydarzen
zalogowany --> propozycjaWydarzenPublicznych
propozycjaWydarzenPublicznych ..> (Wypełnienie formularza\ndotyczącego wydarzenia) : <<include>>
zalogowany -right-> (Zarządzanie swoimi niezatwierdzonymi\npropozycjami wydarzeń - edycja, usuwanie)
zalogowany --> (Tworzenie wydarzeń prywatnych)
(Tworzenie wydarzeń prywatnych) ..> (Wypełnienie formularza\ndotyczącego wydarzenia)  : <<include>>
zalogowany -left-> (Zarządzanie swoimi wydarzeniami\nprywatnymi - edycja, usuwanie)
zalogowany --> (Tworzenie ofert\ndotyczących wydarzeń publicznych)
 (Tworzenie ofert\ndotyczących wydarzeń publicznych) ..> (Wypełnienie formularza dotyczącego oferty) : <<include>>
zalogowany -up-> (Zarządzanie swoimi ofertami\ndo wydarzeń - edycja, usuwanie)
zalogowany -up-> (Odpowiadanie na oferty\ndotyczące wydarzeń publicznych)
zalogowany -up-> (Wyrażenie chęci współudziału\nw wydarzeniu prywatnym)
zalogowany -up--> (Edytowanie profilu)
(Edytowanie profilu) <.right. (Edytowanie wizytówki) : <<extends>>
(Edytowanie profilu) <.right. (Edytowanie preferencji) : <<extends>>

@enduml